import { QuoteState, CapacityRow, SavedComparison, Category } from "./types";

export const INITIAL_STATE: QuoteState = {
  quoteDate: "15/06/2026",
  suppliers: [
    { id: "s1", name: "" },
    { id: "s2", name: "" },
    { id: "s3", name: "" }
  ],
  items: []
};

export const INITIAL_CAPACITY: CapacityRow[] = [
  { month: "jan/26", capacity: 521, value: 4214.28, isEditablePrice: true },
  { month: "fev/26", capacity: 535, value: 3810.29, isEditablePrice: true },
  { month: "mar/26", capacity: 557, value: 4249.14, isEditablePrice: true },
  { month: "abr/26", capacity: 534, value: 3278.51, isEditablePrice: true },
  { month: "mai/26", capacity: 514, value: 3176.85, isEditablePrice: true },
  { month: "jun/26", capacity: 538, value: 0.00, isEditablePrice: true },
  { month: "jul/26", capacity: 545, value: 0.00, isEditablePrice: false }
];

export const INITIAL_SAVED_COMPARISON: SavedComparison = {
  isValid: false,
  savedDate: "",
  monthLabel: "jun/26",
  totals: {
    mixedTotal: 0,
    totalQuantity: 0,
  },
  itemsDetailed: {}
};

export const DEFAULT_CATEGORIES: Category[] = [
  {
    id: "brindes_campanhas",
    name: "BRINDES/CAMPANHAS",
    items: [
      "Bloco de anotações",
      "Botton",
      "Botton / Pin metálico",
      "Caderno",
      "Calendário de mesa",
      "Camiseta promocional",
      "Caneta personalizada",
      "Chaveiro resinado",
      "Copo Stanley personalizado",
      "Ecobag de algodão",
      "Fone bluetooth brinde",
      "Guarda-chuva corporativo",
      "Kit boas-vindas / Onboarding",
      "Mochila para notebook",
      "Squeeze de inox",
      "Necessaire de viagem",
      "Porta-copos emborrachado",
      "Power bank portátil",
      "Sacochila",
      "Tag de mala"
    ]
  },
  {
    id: "cadeiras",
    name: "CADEIRAS",
    items: [
      "Apoio de cabeça regulável",
      "Assento estofado espuma injetada",
      "Banqueta alta para copa",
      "Base estrela cromada",
      "Cadeira de diálogo fixa",
      "Cadeira de tela mesh",
      "Cadeira ergonômica NR17",
      "Cadeira executiva giratória",
      "Cadeira gamer com braço",
      "Cadeira operacional com braço",
      "Cadeira para recepção",
      "Cadeira presidente couro",
      "Encosto em tela sobressalente",
      "Espuma para assento",
      "Longarina 3 lugares",
      "Mecanismo back system",
      "Par de braços reguláveis",
      "Pistão a gás classe 4",
      "Rodízio de nylon sobressalente",
      "Rodízio de silicone (piso frio)"
    ]
  },
  {
    id: "doces",
    name: "DOCES",
    items: [
      "Amendoim salgado pacote",
      "Bala de goma pacote",
      "Bala de hortelã quilo",
      "Bala de menta recepção",
      "Bala mastigável frutas",
      "Barra de cereal chocolate",
      "Barra de cereal morango",
      "Biscoito doce recheado",
      "Bombom sortido caixa",
      "Chiclete menta caixa",
      "Chiclete tutti-frutti",
      "Chocolate meio amargo barra",
      "Doce de leite tablete",
      "Gelatina pronta pote",
      "Marshmallow pacote",
      "Paçoca rolha",
      "Paçoca rolha embalada",
      "Pastilha Tic-Tac",
      "Torrone com amendoim"
    ]
  },
  {
    id: "frete",
    name: "FRETE",
    items: [
      "Advalorem / Seguro carga",
      "Coleta programada",
      "Frete armazenagem temporária",
      "Frete caminhão baú toco",
      "Frete carga pesada prancha",
      "Frete carga seca",
      "Frete coleta de resíduos",
      "Frete container porto",
      "Frete distribuição regional",
      "Frete entrega e-commerce",
      "Frete fracionado interestadual",
      "Frete logística reversa",
      "Frete motoboy urbano",
      "Frete mudança corporativa",
      "Frete paletizado consolidado",
      "Frete retorno de paletes",
      "Frete transporte dedicado",
      "Frete utilitário Fiorino",
      "Taxa de coleta domiciliar",
      "Taxa de descarga"
    ]
  },
  {
    id: "licenca_programas",
    name: "LICENÇA DE PROGRAMAS",
    items: [
      "Antivirus corporativo Endpoint",
      "Assinatura Canva Pro",
      "Assinatura GitHub Enterprise",
      "Assinatura Microsoft 365 Business",
      "Assinatura Slack Pro",
      "Backup em nuvem licença",
      "Licença Adobe Creative Cloud",
      "Licença AutoCAD LT",
      "Licença CorelDraw",
      "Licença ERP SaaS / SAP",
      "Licença Figma Professional",
      "Licença Google Workspace",
      "Licença Jira Software",
      "Licença Miro Team",
      "Licença Salesforce CRM",
      "Licença Trello Premium",
      "Licença Windows 11 Pro",
      "Licença Windows Server CAL",
      "Licença Zoom Meeting 1k",
      "Licença Zoom Meetings Pro"
    ]
  },
  {
    id: "manutencao_cadeiras",
    name: "MANUTENÇÃO DE CADEIRAS",
    items: [
      "Ajuste de contra-peso encosto",
      "Alinhamento de encosto mesh",
      "Fixação de braços frouxos",
      "Lubrificação de engrenagens",
      "Manutenção em braço regulável",
      "Reaperto geral de parafusos",
      "Reforma de cadeira presidente",
      "Revestimento em tecido / Courvin",
      "Serviço de lavagem estofado",
      "Serviço retrofitting de lote",
      "Solda em estrutura metálica",
      "Substituição de base estrela",
      "Substituição de buchas internas",
      "Substituição de capa plástica",
      "Substituição de espuma assento",
      "Substituição de pistão a gás",
      "Troca de eixo de rodízio",
      "Troca de flange de assento",
      "Troca de mecanismo de inclinação",
      "Troca de rodízios danificados"
    ]
  },
  {
    id: "manutencao_computadores",
    name: "MANUTENÇÃO DE COMPUTADORES",
    items: [
      "Ajuste de cabos internos (SATA)",
      "Backup inicial de sistema",
      "Instalação de drivers e softwares",
      "MANUTENÇÃO EM GERAL",
      "Manutenção preventiva anual",
      "Recuperação de dados HD/SSD",
      "Remoção de vírus e malware",
      "Reparo de dobradiça notebook",
      "Reparo em conector Jack DC",
      "Reparo em placa-mãe",
      "Reparo em portas USB físicas",
      "Substituição de battery CMOS",
      "Substituição de HD por SSD",
      "Substituição de teclado notebook",
      "Testes de estresse / Benchmark",
      "Troca de cabo flat interno",
      "Troca de fonte ATX",
      "Troca de placa de rede Wi-Fi",
      "Troca de tela LED notebook",
      "Upgrade de memória RAM"
    ]
  },
  {
    id: "manutencao_head",
    name: "MANUTENÇÃO DE HEAD",
    items: [
      "Abafamento de ruído exterior",
      "Ajuste de ganho física",
      "Conserto de haste flexível",
      "Higienização ultra-sônica lote",
      "Manutenção em controle de volume",
      "Pintura / Restauro estético",
      "Reparo em cabo espiralado",
      "Reparo em headset bluetooth",
      "Solda interna de alto-falante",
      "Substituição de arco de headset",
      "Substituição de cápsula microfone",
      "Substituição de espuma microfone",
      "Substituição de espuma ouvido",
      "Substituição de presilha jacaré",
      "Substituição de protetor de orelha",
      "Troca de almofada de teto",
      "Troca de cabo USB headset",
      "Troca de conector P2/P3",
      "Troca de par de drivers 40mm"
    ]
  },
  {
    id: "material_funcionamento",
    name: "MATERIAL DE FUNCIONAMENTO",
    items: [
      "Amortecedor de impacto silicone",
      "Apagador quadro branco",
      "Bateria CR2032 litio",
      "Benjamin / Adaptador T",
      "Bobina térmica cupom",
      "Calculadora de mesa básica",
      "Chaveiro identificador plástico",
      "Estilete profissional largo",
      "Extensão elétrica 3 pinos",
      "Fita adesiva amarela 50mm",
      "Fita dupla face Fixa Forte",
      "Lâmina estilete reposição",
      "Lixeira de mesa inox",
      "Marcador quadro piloto azul",
      "Organizador gaveta plástico",
      "Pilha alcalina AA",
      "Pilha alcalina AAA",
      "Porta-chaves de parede",
      "Quadro branco 90x60",
      "Tesoura multiuso inox",
      "Trena métrica 5 metros",
      "Adesivo perfurado para vidro"
    ]
  },
  {
    id: "material_funcionamento_grafica",
    name: "MATERIAL DE FUNCIONAMENTO (GRAFICA)",
    items: [
      "Adesivo vinil recorte",
      "BANNER - GERAL",
      "Banner em lona com ilhós",
      "Bloco de notas personalizado",
      "Caderneta capa dura gráfica",
      "Caneca cerâmica com logo",
      "Cardápio / Display acrílico",
      "Cartão de visita Couchê",
      "Catálogo institucional couchê",
      "Cordão de crachá personalizado",
      "Crachá em PVC aproximação",
      "Envelope ofício timbrado",
      "Envelope saco timbrado",
      "Etiqueta adesiva térmica rolo",
      "Flyer institucional colorido",
      "Papel timbrado A4 Offset",
      "Pasta catálogo personalizada",
      "Pasta com orelha personalizada",
      "Sacola de papel personalizada"
    ]
  },
  {
    id: "material_informatica",
    name: "MATERIAL DE INFORMATICA",
    items: [
      "Abraçadeira nylon enforca-gato",
      "Adaptador Bluetooth USB",
      "Adaptador USB-C para HDMI",
      "Base cooler para notebook",
      "Cabo de rede CAT6 patch",
      "Cabo DisplayPort 1.4",
      "Cabo extensor USB 3.0",
      "Cabo HDMI blindado 2m",
      "Carregador notebook universal",
      "Filtro de linha 5 tomadas",
      "Hub USB 4 portas 3.0",
      "Memória RAM DDR4 8GB",
      "Mouse óptico USB básico",
      "Mouse USB óptico com fio",
      "Mousepad ergonômico gel",
      "Pasta térmica Corsair pote",
      "Pen drive 64GB Kingston",
      "SSD 480GB SATA Kingston",
      "Suporte articulado monitor",
      "Teclado USB padrão ABNT2"
    ]
  },
  {
    id: "material_limpeza",
    name: "MATERIAL DE LIMPEZA",
    items: [
      "Álcool em gel 70% - 5L - Pedido SESMET",
      "Cabo Vassoura 150cm",
      "Copo descartável 180ml - cx 25 pct 100un",
      "Desinfetante floral - 5L",
      "Detergente neutro - 5L",
      "Escova de cabo longo para limpeza de cantos",
      "Escova sanitária",
      "Esponja abrasiva mop lava piso",
      "Esponja de louça dupla face",
      "Esponja mágica",
      "Essência",
      "Fibra de limpeza geral - Verde",
      "Flanela de microfibra",
      "Limpador de piso limpeza pesada (mais fraco que removex) 5L",
      "Lustra móveis lavanda - 200ml (preferencia marcas Poliflor, Peroba, UAU)",
      "Luva volk do Brasil, forro Silver tam \"M\" Amarela",
      "Luva volk do Brasil, forro Silver tam \"M\" Azul",
      "MOP pó 60 cm - REFIL",
      "MOP redondo - Refil",
      "Multiuso cremoso - 250ml",
      "Multiuso floral - 5L",
      "Odorizador neutralizador de ambientes - 360ml",
      "Pano de chão - tamanho G",
      "Pano de chão - tamanho M",
      "Pano multiuso (perfex) - rolo 300m",
      "Papel higiênico rolo c/ 300m - fardo",
      "Papel higiênico rolo c/ 300m NOBRE GOEDER - fardo",
      "Rodo para limpar vidros",
      "Rodo twister com cabo",
      "Sabão em pó - 800g",
      "Sabonete líquido perolado - 5L",
      "Saco de lixo 100L (micra 0,7 ou superior) - 100un",
      "Saco de lixo 120L - 100un",
      "Saco De Lixo 60L - 100un",
      "Suporte - Fibra de limpeza geral - Verde",
      "Vassoura pelo"
    ]
  },
  {
    id: "material_limpeza_extra",
    name: "MATERIAL DE LIMPEZA EXTRA",
    items: [
      "Água sanitária 5L",
      "Álcool em gel 70% refil",
      "Álcool líquido 70% 1L",
      "Balde espremedor duas águas",
      "Cera líquida pisos",
      "Cloro em pó frasco",
      "Copo descartável água 200ml",
      "Copo descartável café 50ml",
      "Desinfetante eucalipto galão",
      "Desodorizador ambiente aerossol",
      "Detergente líquido neutro",
      "Escova para vaso sanitário",
      "Esponja dupla face multiuso",
      "Fibra limpeza pesada verde",
      "Fibra macia branca",
      "Guardanapo papel interfolhado",
      "Inseticida spray lata",
      "Limpa-pedras galão",
      "Limpa-vidros frasco",
      "Lustra-móveis tradicional",
      "Luva látex amarela G",
      "Luva látex amarela M",
      "Mop água esfregão completo",
      "Mop pó varrição seco",
      "Multiuso APC frasco",
      "Pano de chão saco",
      "Pano chão alvejado saco",
      "Pano microfibra azul",
      "Pano microfibra verde",
      "Papel higiênico 300m rolo",
      "Papel higiênico folha dupla",
      "Papel toalha interfolhado",
      "Pastilha adesiva vaso",
      "Pedra sanitária bloco",
      "Placa sinalização piso molhado",
      "Pulverizador gatilho plástico",
      "Refil Mop água",
      "Refil Mop pó",
      "Rodo alumínio 40cm",
      "Sabonete espuma premium refil",
      "Sabonete líquido neutro refil",
      "Saco lixo 100L reforçado",
      "Saco lixo 15L",
      "Saco lixo 50L econômico",
      "Saco lixo azul seletivo",
      "Saco lixo transparente",
      "Saponáceo cremoso frasco",
      "Vassoura de pelo macio",
      "Vassoura piaçava externa"
    ]
  },
  {
    id: "material_manutencao",
    name: "MATERIAL DE MANUTENÇÃO",
    items: [
      "Bucha plástica 8mm caixa",
      "Desengripante WD-40 spray",
      "Disjuntor bipolar DIN 20A",
      "Espuma expansiva poliuretano",
      "Fita isolante 3M preta",
      "Fita veda-rosca rolo",
      "Abraçadeira nylon enforca-gato",
      "Lâmpada LED bulbo E27",
      "Lâmpada tubular LED T8",
      "Lixa parede grão 120",
      "Massa corrida balde pequeno",
      "Parafuso soberbo tamanhos caixa",
      "Reparo válvula descarga Hydra",
      "Sela trinca bisnaga",
      "Silicone líquido tubo incolor",
      "Super Bonder cola instantânea",
      "Tinta látex branca galão",
      "Tomada elétrica sobreposição",
      "Torneira metálica parede pia",
      "Trincha de pintura média"
    ]
  },
  {
    id: "material_telefonia",
    name: "MATERIAL DE TELEFONIA",
    items: [
      "Adaptador ATA VOIP Cisco",
      "Alicate crimpador RJ11/RJ45",
      "Aparelho IP sem fio Intelbras",
      "Aparelho telefônico analógico fixo",
      "Bateria para telefone sem fio",
      "Bloco de conexão IDC Krone",
      "Cabo telefônico CCE 1 par",
      "Cabo telefônico espiral fone",
      "Cabo telefônico liso RJ11",
      "Central PABX rack módulo",
      "Conector RJ11 pacote",
      "Distribuidor Geral Telefonia DG",
      "FIO FE de espinar rolo",
      "Fonte de alimentação 12V Intelbras",
      "Headset telefônico RJ9",
      "Identificador de chamadas bina",
      "Interface celular / Interface GSM",
      "Patch panel telefônico 30p",
      "Placa de tronco IP",
      "Protetor de surto linha telefônica",
      "Telefone Headset RJ9"
    ]
  },
  {
    id: "material_escritorio",
    name: "MATERIAL DO ESCRITORIO",
    items: [
      "Bloco notas adesivas Post-it",
      "Borracha branca escolar",
      "Caderno capa dura Ata",
      "Caneta esferográfica azul caixa",
      "Caneta esferográfica preta caixa",
      "Clips para papel 3/0",
      "Durex fino rolo",
      "Extrator de grampos inox",
      "Fita adesiva larga transparente",
      "Grampeador de mesa médio",
      "Grampos 26/6 caixa",
      "Lápis preto HB caixa",
      "Marcador texto amarelo caixa",
      "Organizador de mesa plástico",
      "Papel sulfite A4 resma",
      "Pasta AZ lombo largo",
      "Pasta plástica elástico azul",
      "Pasta suspensa Kraft caixa",
      "Perfurador de papel inox"
    ]
  },
  {
    id: "micro_computador",
    name: "MICRO COMPUTADOR",
    items: [
      "All in One LG 24\"",
      "Computador corporativo Lenovo i5",
      "Computador montado Ryzen 5",
      "Cooler processador Noctua",
      "Desktop Dell Optiplex 16GB",
      "Desktop HP ProDesk i7 16GB",
      "Estação de trabalho Xeon 32GB",
      "Fonte Corsair 550W",
      "Gabinete ATX básico preto",
      "Gravador BD interno SATA",
      "Gravador DVD externo USB",
      "HD interno 1TB Seagate",
      "Kit teclado e mouse com fio",
      "Mini PC Beelink",
      "Monitor Dell 23.8\" IPS",
      "Placa de som PCI Express",
      "Placa de vídeo GTX 1650",
      "Placa-mãe Asus Prime B450",
      "SSD M.2 NVMe 500GB Crucial",
      "Suporte CPU de rodízio"
    ]
  },
  {
    id: "moveis",
    name: "MÓVEIS",
    items: [
      "Aparador decorativo recepção",
      "Armário alto duas portas",
      "Armário baixo duas portas",
      "Balcão de recepção reto",
      "Bandeja porta-teclado retrátil",
      "Biombo divisor de ambientes",
      "Credenza executiva escritório",
      "Estante de metal 5 prateleiras",
      "Estante de aço 6 prateleiras",
      "Gaveteiro volante 3 gavetas",
      "Lockers guarda-volumes 10 portas",
      "Mesa de centro recepção",
      "Mesa de reunião 6 lugares",
      "Mesa diretor em L",
      "Mesa operacional reta 120cm",
      "Mesa para refeitório 4 lug",
      "Nicho de parede para livros",
      "Painel para TV sala",
      "Passa-cabos plástico mesa",
      "Suporte CPU suspenso MDF"
    ]
  },
  {
    id: "notebook",
    name: "NOTEBOOK",
    items: [
      "Bateria notebook reposição HP",
      "Cabo segurança notebook Kensington",
      "Cadeado de segurança notebook",
      "Carregador original Dell 65W",
      "Carregador original Lenovo Type-C",
      "Case notebook neoprene 14\"",
      "ChromeBook Asus 4GB 128GB",
      "Maleta notebook executiva 15\"",
      "Notebook Acer Aspire 3",
      "Notebook Asus Vivobook 15",
      "Notebook corporativo Positivo",
      "Notebook Dell Latitude Core i5",
      "Notebook Dell Vostro i7 Nvidia",
      "Notebook gamer Acer Nitro i7",
      "Notebook HP ProBook i5 8GB",
      "Notebook Lenovo ThinkPad i7",
      "Notebook ultraframe Samsung",
      "Película fosca anti-reflexo",
      "Teclado reposição ThinkPad",
      "Tela LED slim 15.6\" notebook"
    ]
  },
  {
    id: "refeicao_cafe_frutas",
    name: "REFEIÇÃO (CAFÉ, FRUTAS)",
    items: [
      "Adoçante líquido 100ml",
      "Açúcar refinado sachê caixa",
      "Adoçante líquido sucralose frasco",
      "Adoçante sachê caixa",
      "Água mineral com gás 500ml",
      "Água mineral sem gás 500ml",
      "Banana prata entrega semanal",
      "Biscoito Cream Cracker pacote",
      "Biscoito Maizena pacote",
      "Café em pó a vácuo 500g",
      "Café em pó vácuo 500g",
      "Cápsula Dolce Gusto Café",
      "Cápsula Nespresso Espresso",
      "Chá camomila saquinho caixa",
      "Chá erva-doce saquinho 24p",
      "Cookies chocolate pacote",
      "Galão água mineral 20L",
      "Leite em pó integral sachê",
      "Leite integral UHT 1L",
      "Maçã nacional entrega semanal"
    ]
  },
  {
    id: "reforma",
    name: "REFORMA",
    items: [
      "Bancada granito sob medida",
      "Cuba inox para pia cozinha",
      "Divisória naval instalada m²",
      "Fechadura digital embutir",
      "Forro drywall estruturado m²",
      "Forro gesso acartonado m²",
      "Instalação de ar condicionado",
      "Instalação luminária LED spot",
      "Luminária LED embutir 30W",
      "Pintura interna paredes m²",
      "Piso vinílico instalado m²",
      "Porcelanato retificado m²",
      "Porta de vidro temperado 10mm",
      "Ralo linear invisível aço",
      "Remoção de entulho caçamba",
      "Revestimento cerâmico parede m²",
      "Rodapé poliestireno metro",
      "Sensor de presença teto",
      "Serviço impermeabilização laje",
      "Troca de fiação de rede lógica"
    ]
  },
  {
    id: "servicos_manutencao",
    name: "SERVIÇOS DE MANUTENÇÃO",
    items: [
      "Aferição de para-raios SPDA",
      "Desentupimento de esgoto encanamento",
      "Desinsetização predial completa",
      "Limpeza de caixa d'água",
      "Limpeza de calhas telhado",
      "Limpeza de fachada predial",
      "Manutenção CFTV câmeras",
      "Manutenção de bomba de recalque",
      "Manutenção de cerca elétrica",
      "Manutenção de elevador mensal",
      "Manutenção de painel solar",
      "Manutenção de portão eletrônico",
      "Manutenção preventiva ar condicionado",
      "Recarga de extintores incêndio",
      "Reparo de infiltrações e telhado",
      "Reparo hidráulico torneiras",
      "Revisão de quadro elétrico",
      "Revisão sistema de alarme",
      "Troca de vidros quebrados"
    ]
  },
  {
    id: "sesmt",
    name: "SESMT",
    items: [
      "Abafador ruído concha tipo arco",
      "Abafador de ruídos silicone",
      "Bota de segurança com biqueira",
      "Capacete de segurança aba frontal",
      "Cavalete de sinalização Atenção",
      "Cavalete sinalização Saída Emergência",
      "Cone de sinalização refletivo 75cm",
      "Creme de proteção luva química",
      "Extintor de incêndio PQS 4kg",
      "Fita antiderrapante para escadas",
      "Fita zebrada rolo 200m",
      "Luva raspa de couro cano longo",
      "Luva vaqueta cano curto",
      "Maleta de primeiros socorros cheia",
      "Mangote de raspa proteção braço",
      "Óculos de proteção incolor",
      "Óculos segurança lente incolor",
      "Protetor auricular plug silicone",
      "Respirador PFF2 / N95 com válvula"
    ]
  },
  {
    id: "sesmet_dedetizacao",
    name: "SESMET DEDETIZAÇÃO",
    items: [
      "Aplicação gel baratas fendas",
      "Atomização de inseticida copas",
      "Controle de escorpiões aplicação",
      "Controle de morcegos desalojamento",
      "Dedetização baratas barreira física",
      "Dedetização baratas e formigas",
      "Dedetização de aranhas cantos",
      "Dedetização de mosquitos pulverização",
      "Dedetização de pulgas e carrapatos",
      "Desinsetização contra moscas",
      "Descupinização tratamento madeira",
      "Descupinização tratamento solo",
      "Desratização com iscas blocos",
      "Higienização reservatório água",
      "Laudo técnico de controle vetorial",
      "Limpeza e desinfecção caixa d'água",
      "Polvilhamento químico frestas/ralos",
      "Refil placa colante para armadilha",
      "Tratamento cupim de solo localizado",
      "Termonebulização áreas abertas"
    ]
  },
  {
    id: "switch",
    name: "SWITCH",
    items: [
      "Abraçadeira velcro rolo organizador",
      "Cabo console RJ45 para DB9",
      "Cabo empilhamento DAC Switch",
      "Cordão óptico monomodo LC-LC",
      "Guia de cabos horizontal 1U",
      "Injetor PoE individual TP-Link",
      "Kit fixação rack porca gaiola",
      "Módulo Transceiver SFP+ 10G MiniGbic",
      "Nobreak senoidal rack 1.5kVA",
      "Organizador vertical de cabos rack",
      "Patch panel 24 portas CAT6",
      "Switch Aruba 48 portas PoE+",
      "Switch Cisco 24 portas Gigabit",
      "Switch Edgecore 8 portas PoE+",
      "Switch Huawei CloudEngine L3",
      "Switch industrial trilho DIN",
      "Switch MikroTik RouterBoard",
      "Switch TP-Link 16p rack",
      "Switch TP-Link 24p",
      "Switch Ubiquiti UniFi 8p"
    ]
  }
];

export const FACILITIES_MATERIALS_PRESET: string[] = Array.from(
  new Set(DEFAULT_CATEGORIES.flatMap((cat) => cat.items))
);
